#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Karabiner-Elements — Caps Lock 短按切输入法 / 长按大小写锁
# 语义对齐 keyd 的 timeout(f14, 250, capslock)：
#   短按 (<250ms) → f18 → 系统快捷键"选择下一个输入法"
#   长按 (>=250ms) → 真 caps_lock（切换大小写锁）
# 每个阶段自动追加时间戳到过程日志（博客素材）。
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

RESEARCH_DIR="${RESEARCH_DIR:-${TMPDIR:-/tmp}/capslock-research}"
LOG_FILE="${LOG_FILE:-$RESEARCH_DIR/setup-log.md}"
KE_RULE_FILE="$HOME/.config/karabiner/assets/complex_modifications/capslock-tap-f18-hold-capslock.json"
KE_CONFIG="$HOME/.config/karabiner/karabiner.json"
TAP_HOLD_MS=250   # 与下面 JSON 里的 250 保持一致

mkdir -p "$RESEARCH_DIR"

log() {
  printf -- '- %s · %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*" >> "$LOG_FILE"
}

[[ -f "$LOG_FILE" ]] || {
  printf '# Karabiner Caps Lock 修复过程日志\n\n> 由 wizard-karabiner-capslock.sh 自动生成。\n\n' > "$LOG_FILE"
}
log "wizard started; tap/hold threshold ${TAP_HOLD_MS}ms"

banner "Karabiner-Elements: Caps Lock 短按切输入法 / 长按大小写锁"

# ── Stage 1: 安装 ─────────────────────────────────────────────────────────
stage "安装 Karabiner-Elements"
say "优先用 Homebrew 安装（cask: karabiner-elements，pkg 安装器）；装失败或没有 brew 才走官网下载。"
note "pkg 安装器可能弹出 GUI，或在终端要求一次管理员密码。"
if command -v brew >/dev/null 2>&1; then
  pause "看清楚后按回车，开始 brew 安装"
  if confirm "现在运行 brew install --cask karabiner-elements？"; then
    if brew install --cask karabiner-elements; then
      KE_VERSION=$(brew list --cask --versions karabiner-elements 2>/dev/null | awk '{print $2}' || true)
      say "✓ 安装完成，版本：${KE_VERSION:-未知}"
      log "installed Karabiner-Elements ${KE_VERSION:-unknown} via brew cask"
    else
      warn "brew 安装失败，回退到官网下载。"
      log "brew install --cask karabiner-elements FAILED"
      pause "按回车后我帮你打开官网下载页"
      open_url "https://karabiner-elements.pqrs.org/"
      SKIPPED+=("安装 Karabiner-Elements（brew 失败，改官网手动安装）")
    fi
  else
    warn "已跳过 brew 安装；若要手动安装，按回车打开官网下载页。"
    pause "按回车打开官网（或自行手动安装）"
    open_url "https://karabiner-elements.pqrs.org/"
    SKIPPED+=("安装 Karabiner-Elements（本轮跳过）")
    log "brew install skipped by user"
  fi
else
  warn "未找到 brew，改用官网下载安装。"
  pause "按回车后我帮你打开官网下载页"
  open_url "https://karabiner-elements.pqrs.org/"
  SKIPPED+=("安装 Karabiner-Elements（无 brew，官网手动）")
fi
pause "安装完成后按回车继续"

# ── Stage 2: DriverKit 系统扩展 ───────────────────────────────────────────
stage "批准 DriverKit 系统扩展"
say "先启动一次 Karabiner-Elements：系统设置里的 Karabiner 条目要等它运行后才出现。"
pause "按回车后我会启动 Karabiner-Elements"
open -a Karabiner-Elements 2>/dev/null || warn "启动失败：请确认已安装，或手动打开 Karabiner-Elements"
note "如果它弹出引导/权限提示，先看完再继续。"
step "然后打开「系统设置 → 扩展 → 按类别 → 驱动程序扩展」（macOS Tahoe 实际路径）。"
note "旧版 macOS 在「通用 → 登录项与扩展 → 驱动程序扩展」；面板不对就按上述路径手动导航。"
pause "看清楚路径后按回车，我再帮你打开系统设置"
open_url "x-apple.systempreferences:com.apple.LoginItems-Settings.extension"
step "找到 Karabiner-DriverKit-VirtualHIDDevice（org.pqrs.Karabiner-DriverKit-VirtualHIDDevice），把开关打开。"
note "若弹出『系统软件已被阻止/需要批准』的提示：点允许，或到上述页面开启。"
warn "macOS 可能要求重新启动一次。需要的话请现在重启，之后重新运行本向导（可跳过已完成步骤）。"
pause "批准完成后按回车继续（若重启了，重启后再运行）"
EXT_STATE=$(systemextensionsctl list 2>/dev/null | grep -i "org\.pqrs" || true)
if [[ -n "$EXT_STATE" && "$EXT_STATE" == *"activated"* && "$EXT_STATE" != *"waiting for user"* ]]; then
  say "✓ DriverKit 扩展已激活："
  note "  $EXT_STATE"
  log "driver extension activated: $EXT_STATE"
else
  warn "DriverKit 扩展尚未就绪（需要在系统设置里批准，或重启）："
  note "  ${EXT_STATE:-（systemextensionsctl 中未见 org.pqrs 扩展）}"
  log "driver extension NOT ready: ${EXT_STATE:-not listed}"
  SKIPPED+=("DriverKit 系统扩展批准（状态非 activated）")
fi
pause "按回车继续"

# ── Stage 3: 授权 ─────────────────────────────────────────────────────────
stage "授权：后台服务 + 辅助功能"
say "KE 官方要求的 macOS 设置清单："
pause "看清楚后按回车，我再打开 KE 官方文档参考页"
open_url "https://karabiner-elements.pqrs.org/docs/manual/misc/required-macos-settings/"
step "1) 打开 Karabiner 的后台服务开关。"
note "（Tahoe：若找不到「登录项与扩展」，相关开关可能在「扩展」面板里；以你实际看到的 UI 为准。）"
pause "看清楚后按回车，我再帮你打开系统设置"
open_url "x-apple.systempreferences:com.apple.LoginItems-Settings.extension"
pause "后台服务开启后按回车，继续打开辅助功能页面"
step "2) 系统设置 → 隐私与安全性 → 辅助功能：允许 Karabiner-Elements / Karabiner-Core-Service。"
open_url "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility"
note "KE 15.10+ 不再要求『输入监控（Input Monitoring）』；仅当系统明确提示时才去开。"
pause "授权完成后按回车继续"
if pgrep -i karabiner >/dev/null 2>&1; then
  say "✓ Karabiner 进程正在运行。"
  log "karabiner processes running after permissions"
else
  warn "未见 Karabiner 进程。请确认授权生效，必要时退出并重新打开 Karabiner-Elements。"
  log "karabiner processes NOT running after permissions"
  SKIPPED+=("后台服务/辅助功能授权确认")
fi
pause "按回车继续"

# ── Stage 4: 规则文件 + 启用 ──────────────────────────────────────────────
stage "写入并启用 Caps Lock 双功能规则"
say "规则语义（对齐 keyd 的 timeout(f14, ${TAP_HOLD_MS}, capslock)）："
note "  短按（<${TAP_HOLD_MS}ms）→ F18 → 触发系统『选择下一个输入法』"
note "  长按（≥${TAP_HOLD_MS}ms）→ 真 Caps Lock（切换大小写锁一次）"
if [[ -f "$KE_RULE_FILE" ]] && ! confirm "规则文件已存在，覆盖重写？"; then
  say "保留现有规则文件：$KE_RULE_FILE"
  log "KE rule file kept (user declined overwrite)"
else
  mkdir -p "$(dirname "$KE_RULE_FILE")"
  cat > "$KE_RULE_FILE" <<'KEJSON'
{
  "title": "Caps Lock: tap → F18 (switch input source), hold → Caps Lock",
  "rules": [
    {
      "description": "Caps Lock: tap → F18 (select next input source), hold (≥250ms) → Caps Lock toggle",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "caps_lock",
            "modifiers": { "optional": ["any"] }
          },
          "to_if_alone": [{ "key_code": "f18" }],
          "to_if_held_down": [
            {
              "key_code": "caps_lock",
              "hold_down_milliseconds": 200
            }
          ],
          "parameters": {
            "basic.to_if_alone_timeout_milliseconds": 250,
            "basic.to_if_held_down_threshold_milliseconds": 250
          }
        }
      ]
    }
  ]
}
KEJSON
  say "✓ 已写入 $KE_RULE_FILE"
  log "wrote KE complex modification rule file"
fi
say "接下来在 KE 里启用规则（先看清楚步骤，我再帮你打开应用）："
step "在 KE 里进入 Complex Modifications → Add rule。"
step "在规则列表找到 \"Caps Lock: tap → F18 (switch input source), hold → Caps Lock\"，点 Enable。"
note "规则来源目录：~/.config/karabiner/assets/complex_modifications/"
pause "看清楚后按回车，我会打开 Karabiner-Elements"
open -a Karabiner-Elements 2>/dev/null || open_url "https://karabiner-elements.pqrs.org/docs/manual/configuration/configure-complex-modifications/"
pause "启用后按回车，向导会检查配置"
if command -v jq >/dev/null 2>&1 && [[ -f "$KE_CONFIG" ]]; then
  if jq -e '[.profiles[]?.complex_modifications.rules[]? | select(.enabled != false) | .manipulators[]? | select(.from.key_code == "caps_lock" and .to_if_held_down != null)] | length > 0' "$KE_CONFIG" >/dev/null 2>&1; then
    say "✓ karabiner.json 中规则已启用。"
    log "KE rule enabled in karabiner.json (jq check)"
  else
    warn "karabiner.json 中尚未检测到启用的规则——请回到 KE 点 Enable。"
    log "KE rule NOT enabled in karabiner.json yet"
    SKIPPED+=("在 Karabiner-Elements 中 Enable 该规则")
  fi
elif [[ -f "$KE_CONFIG" ]] && grep -q '"to_if_held_down"' "$KE_CONFIG"; then
  say "✓ karabiner.json 中检测到 to_if_held_down（规则应已启用；无 jq，未逐项校验）。"
  log "KE rule likely enabled (grep to_if_held_down; jq unavailable)"
else
  warn "karabiner.json 尚不存在或未见规则——请在 KE 中启用规则后重新运行向导校验。"
  log "KE rule not verifiable (no karabiner.json match)"
  SKIPPED+=("在 Karabiner-Elements 中 Enable 该规则")
fi
pause "按回车继续"

# ── Stage 5: F18 绑定系统快捷键 ───────────────────────────────────────────
stage "把 F18 绑到『选择下一个输入法』"
say "先看清楚步骤，我再帮你打开系统设置："
step "「系统设置 → 键盘 → 键盘快捷键… → 输入法」。"
step "选中「选择『输入』菜单中的下一个输入法」(Select next source in Input menu)，点快捷键栏，按 F18。"
warn "MacBook 内置键盘没有 F18 实体键：上一步规则已生效，直接**快按一下 Caps Lock**（它现在就是 F18）即可录进快捷键。"
note "注意录快捷键时按得快一点（<${TAP_HOLD_MS}ms），否则录到的是 Caps Lock。"
note "不要改用 Karabiner 的 select_input_source 切中文输入法：官方文档明确它对 CJKV 输入法会失败。"
pause "看清楚后按回车，我再帮你打开系统设置"
open_url "x-apple.systempreferences:com.apple.Keyboard-Settings.extension"
log "instructed: bind F18 (or tapped caps_lock) to 'Select next source in Input menu'"
pause "绑定完成后按回车继续"

# ── Stage 6: 关闭 Caps Lock ↔ ABC 切换 ────────────────────────────────────
stage "关闭『使用 Caps Lock 键切换到和从 ABC』"
note "不关的话，长按发出的 Caps Lock 会被系统的 ABC 切换吞掉，而不是切换大小写锁。"
TIS_BEFORE=$(defaults read com.apple.HIToolbox TISRomanSwitchState 2>/dev/null || echo "unset")
step "打开「系统设置 → 键盘 → 文本输入 → 输入法 → 编辑…」，取消勾选『使用 Caps Lock 键切换到和从 ABC 切换』。"
pause "看清楚后按回车，我再帮你打开系统设置"
open_url "x-apple.systempreferences:com.apple.Keyboard-Settings.extension"
pause "取消勾选后按回车继续"
TIS_AFTER=$(defaults read com.apple.HIToolbox TISRomanSwitchState 2>/dev/null || echo "unset")
say "TISRomanSwitchState: ${TIS_BEFORE} → ${TIS_AFTER}"
note "（该键与开关的对应关系未经证实，仅作观察记录，勿写成结论。）"
log "toggled off 'Use Caps Lock to switch to and from ABC'; TISRomanSwitchState ${TIS_BEFORE} -> ${TIS_AFTER} (mapping unverified)"
pause "按回车继续"

# ── Stage 7: 验证 ─────────────────────────────────────────────────────────
stage "验证：短按切输入法 / 长按大小写锁"
step "启动 Karabiner-EventViewer，看按键事件是否即时、短按是否发出 f18。"
pause "看清楚后按回车，我再启动 Karabiner-EventViewer"
if open -a Karabiner-EventViewer 2>/dev/null; then
  say "  （已启动 Karabiner-EventViewer）"
else
  EV_APP=$(find /Applications/Karabiner-Elements.app -maxdepth 4 -name "Karabiner-EventViewer.app" 2>/dev/null | head -n1 || true)
  if [[ -n "$EV_APP" ]]; then
    open "$EV_APP" 2>/dev/null || true
    say "  （已启动 $EV_APP）"
  else
    warn "没找到 Karabiner-EventViewer；可在 Karabiner-Elements 菜单里找 'EventViewer'。"
  fi
fi
say "逐项测试："
step "1) 快按 Caps Lock（<${TAP_HOLD_MS}ms）→ 输入法应立即切换；EventViewer 里看到 f18。"
step "2) 长按 Caps Lock（≥${TAP_HOLD_MS}ms）→ 大写锁切换一次（屏幕出现大写指示）。"
step "3) 再长按一次 → 大写锁关闭。"
step "4) 正常打字：无额外延迟、无丢键。"
step "5) （可选，博客素材）凭手感对比修复前的几百毫秒延迟，记下主观感受。"
if confirm "以上全部通过？"; then
  say "✓ 验证通过"
  log "verification PASSED (user confirmed tap=switch, hold=caps lock)"
else
  warn "未全部通过。常见原因：规则未 Enable、辅助功能/后台服务未授权、F18 未绑定、ABC 开关未关。"
  warn "仍不行的话，之后可以用 diagnosing-bugs 做二次定位（HID 层 vs IMK 层）。"
  log "verification FAILED or partial (user-reported)"
  SKIPPED+=("验证未完全通过，需排查（规则启用/授权/F18 绑定/ABC 开关）")
fi
pause "按回车查看收尾说明"

# ── Stage 8: 收尾 ─────────────────────────────────────────────────────────
stage "收尾与回滚"
say "回滚方式（如需撤销）："
step "· 只停用映射：Karabiner-Elements → Complex Modifications → 该规则 → Disable。"
step "· 恢复原生行为：系统设置重新勾选『使用 Caps Lock 键切换到和从 ABC』，并清掉 F18 快捷键绑定。"
step "· 彻底卸载：brew uninstall --cask karabiner-elements（官方卸载器会移除 DriverKit 扩展）。"
say ""
say "过程日志（博客『配置过程』章节素材）："
note "  $LOG_FILE"
note "  KE 规则文件：$KE_RULE_FILE"
warn "提醒：Caps Lock 现在不再是'即按即大写锁'——短按是切输入法，长按才是大写锁（与 keyd 配置同语义）。"
log "wizard finished"
pause "按回车查看总结"

finish
